= Docker container Angular

This repository contains configurations to create a Docker container with:
- *nodejs* v7.+ and npm 
- *angular-cli* latest version
- *Apache2*

This container needs an Angular project to work. At the running, it will download npm packages and build the project.

Like that, after few secondes/minutes, your Angular website works.

== Getting Started

=== Prerequisites

You have to install *Docker* and *Docker Compose* (optional) to build and run this container.

=== Build container

To build the container in local, you can launch this script :

[source,bash]
----
./build.sh
----

=== Pull container

You can download this container from *DockerHub* by launching this command :

[source,bash]
----
docker pull lparet/docker-angular
----

It will download the latest version.

=== Run container

==== Prerequisites

Firstly, you have to plug a Angular project. To do that, you need to create a *data volume* between host and docker container.

- Pull your project in a directory on your host.
- Copy it path in *docker-compose.yml* and edit */path/to/your/project*

.docker-compose.yml
----
services:
  docker-angular:
    image: lparet/docker-angular:0.1
    container_name: docker-angular
    restart: always
    volumes:
      - /path/to/your/project:/var/www/html:rw
----

==== Running

You can use *docker-compose.yml*:

[source,bash]
----
docker-compose up -d
----

It will run your container with parameters specified in the file.

=== Test your project

Open in your browser this URL http://localhost:80

OR

Consult Docker container logs

[source,bash]
----
docker logs docker-angular
----

OR

[source,bash]
----
docker exec -it docker-angular bash
----

== Author

Louis Paret - perso@louisparet.fr
